### ISSUE TITLE
Privman doc correction

### ISSUE THREAD

**Issue by vnigam** [thycotic/privman-docs#120]
Document: (https://docs.thycotic.com/privman/10.8.2/pm-intro)

Looks like a typo in the following sentence in the "Active Directory and Azure Active Directory" section: 

- such as adding a user to a local administrator account – can’t be blocked automatically and in real time

Should have been 'can' instead of 'can't'. Review and correct as needed.

**Comment by danigran** [comment]
Resolved in the latest documentation update.
Thank you for your input!
