### ISSUE TITLE
Change sequence of ServiceNow integration

### ISSUE THREAD

**Issue by nikhilrao123** [thycotic/privman-docs#124]
Document: (https://docs.thycotic.com/privman/11.0.0/admin/config/foreign-systems/third-party/set-up-servicenow.md)

There is a product bug which is causing failure while integrating PMC with ServiceNow. As advised by the support agent (Support case #00401211), please change the order of the steps to be executed in the documentation so that others are able to follow through without hitting any roadblocks.

**Comment by danigran** [comment]
This issue is under investigation and has been moved to an internal issue tracking system.
