### ISSUE TITLE
Priorities mentioned in example policy are not correct. 

### ISSUE THREAD

**Issue by jhiltontsi** [thycotic/privman-docs#125]
Document: (https://docs.thycotic.com/privman/11.0.0/computer-groups/app-control/policies/priority.md)

Hello,

There are mismatches between the correct policy priority values and what is displayed in both the text and screenshots. 

![image](https://user-images.githubusercontent.com/80361039/110537594-e2c50080-80f0-11eb-8ba3-c2b4ea63f9d7.png)

Thanks!

**Comment by danigran** [comment]
These are **examples**. Based on your environment you might want to use different numbers. The main rule to follow is that blocking policies should be processed before monitoring policies that you use for discovery on a limited set of machines. Somewhere in between the low blocking and high monitoring number range you have to place your elevation and allow policies. 

Updated screenshots for the **examples** will be added via one of our next documentation updates.

Thank you for your feedback!
